In [ ]:
# Setup
!pip install pandas numpy
import pandas as pd

In [16]:
#import and inspect data

#entity, the name of the country, region, or income bracket
#code, the three-letter country code
# year, the year
#internet_users_per_100, the number of internet users for every 100 people in the entity's population


internet = pd.read_csv('internet.csv')
internet.head()

        entity code  year  internet_users_per_100
0  Afghanistan  AFG  1990                     0.0
1  Afghanistan  AFG  1991                     0.0
2  Afghanistan  AFG  1992                     0.0
3  Afghanistan  AFG  1993                     0.0
4  Afghanistan  AFG  1994                     0.0

In [ ]:
internet.rename(columns={'internet_users_per_100':'percent_online'}, inplace=True)
internet.info()

<class 'pandas.DataFrame'>
RangeIndex: 6367 entries, 0 to 6366
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   entity          6367 non-null   str
 1   code            6367 non-null   str
 2   year            6367 non-null   int64
 3   percent_online  6367 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 199.1 KB

        entity code  year  percent_online
0  Afghanistan  AFG  1990             0.0
1  Afghanistan  AFG  1991             0.0
2  Afghanistan  AFG  1992             0.0
3  Afghanistan  AFG  1993             0.0
4  Afghanistan  AFG  1994             0.0

In [ ]:
#Years to Reach Mainstream Use
#Calculates how long it takes for internet use to reach the majority of people in an entity using the percent_online column. The function will return a string indicating whether the entity has no internet use, few people online, some people online, or most people online.

def internet_use_by_entity(row):
    if row['percent_online'] == 0:
        return 'none'
    elif row['percent_online'] > 0 and row['percent_online'] < 25:
        return 'few'
    elif row['percent_online'] >= 25 and row['percent_online'] < 50:
        return 'some'
    else:
        return 'most'
    
#Create a new column named amount_online on internet by applying the function internet_use_by_entity to each row
    
internet['amount_online'] = internet.apply(internet_use_by_entity, axis=1)
internet.head()